//存放页面数据
module.exports = {
    getSort(){
        let a = {
            snSortListInfo:[
                 {
                    id:0,
                    title:'热门推荐',
                goodsInfo:[
                    {
                        id:0,
                        words:'空调',
                        src:'./images/1526974072412_app_wap_list.jpg'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1491712405935_pc_list.jpg'
                    }
                ]
            },
            {
                id:1,
                title:'手机数码'
            },
            {
                id:2,
                title:'大家电'
            },
            {
                id:3,
                title:'电脑办公'
            },
            {
                id:4,
                title:'厨卫大电'
            },
            {
                id:5,
                title:'生活家电'
            },
            {
                id:6,
                title:'食品酒水'
            },
            {
                id:7,
                title:'品质男装'
            },
            {
                id:8,
                title:'苏宁国际'
            },
            {
                id:9,
                title:'家居家纺'
            },
            {
                id:10,
                title:'运动户外'
            },
            {
                id:11,
                title:'居家生活'
            },
            {
                id:12,
                title:'珠宝首饰'
            },
            {
                id:13,
                title:'家装建材'
            },
            {
                id:14,
                title:'厨具水具'
            },
            {
                id:15,
                title:'二手优品'
            },
            {
                id:16,
                title:'苏宁生鲜'
            },
        ],
            goodsLIst:[
            {
                name:'热门搜索',
                id:1,
                list:[
                    {
                        gid:0,
                        src:'./images/1526974072412_app_wap_list.jpg',
                        words:'空调'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1493018450115_pc_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1526974072412_app_wap_list.jpg',
                        words:'空调'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1493018450115_pc_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1526974072412_app_wap_list.jpg',
                        words:'空调'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1493018450115_pc_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1526974072412_app_wap_list.jpg',
                        words:'空调'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1493018450115_pc_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1526974072412_app_wap_list.jpg',
                        words:'空调'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1493018450115_pc_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1526974072412_app_wap_list.jpg',
                        words:'空调'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1493018450115_pc_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1526974072412_app_wap_list.jpg',
                        words:'空调'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1493018450115_pc_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1526974072412_app_wap_list.jpg',
                        words:'空调'
                    },
                    {
                        id:1,
                        words:'电视',
                        src:'./images/1491712405935_pc_list.jpg'
                    },
                    {
                        id:2,
                        words:'洗衣机',
                        src:'./images/1493018450115_pc_list.jpg'
                    }
                ]
            },
            {
                name:'手机数码',
                id:0,
                list:[
                    {
                        gid:0,
                        src:'./images/1493946827440_app_list.jpg',
                        words:'电脑'
                    },
                    {
                        id:1,
                        words:'paid',
                        src:'./images/1493946924941_app_list.jpg'
                    },
                    {
                        id:2,
                        words:'数码',
                        src:'./images/1493946999339_app_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1493946827440_app_list.jpg',
                        words:'电脑'
                    },
                    {
                        id:1,
                        words:'paid',
                        src:'./images/1493946924941_app_list.jpg'
                    },
                    {
                        id:2,
                        words:'数码',
                        src:'./images/1493946999339_app_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1493946827440_app_list.jpg',
                        words:'电脑'
                    },
                    {
                        id:1,
                        words:'paid',
                        src:'./images/1493946924941_app_list.jpg'
                    },
                    {
                        id:2,
                        words:'数码',
                        src:'./images/1493946999339_app_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1493946827440_app_list.jpg',
                        words:'电脑'
                    },
                    {
                        id:1,
                        words:'paid',
                        src:'./images/1493946924941_app_list.jpg'
                    },
                    {
                        id:2,
                        words:'数码',
                        src:'./images/1493946999339_app_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1493946827440_app_list.jpg',
                        words:'电脑'
                    },
                    {
                        id:1,
                        words:'paid',
                        src:'./images/1493946924941_app_list.jpg'
                    },
                    {
                        id:2,
                        words:'数码',
                        src:'./images/1493946999339_app_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1493946827440_app_list.jpg',
                        words:'电脑'
                    },
                    {
                        id:1,
                        words:'paid',
                        src:'./images/1493946924941_app_list.jpg'
                    },
                    {
                        id:2,
                        words:'数码',
                        src:'./images/1493946999339_app_list.jpg'
                    },
                    {
                        gid:0,
                        src:'./images/1493946827440_app_list.jpg',
                        words:'电脑'
                    },
                    {
                        id:1,
                        words:'paid',
                        src:'./images/1493946924941_app_list.jpg'
                    },
                    {
                        id:2,
                        words:'数码',
                        src:'./images/1493946999339_app_list.jpg'
                    }
                ]
            },
                {
                    name:'大家电',
                    id:0,
                    list:[
                        {
                            gid:0,
                            src:'./images/1493019147058_pc_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1565254593244_imgWap_tmndir.png'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1526959930017_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493019147058_pc_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1565254593244_imgWap_tmndir.png'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1526959930017_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493019147058_pc_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1565254593244_imgWap_tmndir.png'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1526959930017_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493019147058_pc_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1565254593244_imgWap_tmndir.png'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1526959930017_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493019147058_pc_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1565254593244_imgWap_tmndir.png'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1526959930017_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493019147058_pc_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1565254593244_imgWap_tmndir.png'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1526959930017_imgWap_tmndir.png'
                        }
                    ]
                },
                {
                    name:'电脑办公',
                    id:0,
                    list:[
                        {
                            gid:0,
                            src:'./images/1493947041765_app_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1493946999339_app_list.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1493946924941_app_list.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1554794058372_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493947041765_app_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1493946999339_app_list.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1493946924941_app_list.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1554794058372_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493947041765_app_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1493946999339_app_list.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1493946924941_app_list.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1554794058372_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493947041765_app_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1493946999339_app_list.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1493946924941_app_list.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1554794058372_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            gid:0,
                            src:'./images/1493947041765_app_list.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1493946999339_app_list.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1493946924941_app_list.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1554794058372_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1565060621984_imgWap_tmndir.png'
                        }
                    ]
                },
                {
                    name:'厨卫大电',
                    id:0,
                    list:[
                        {
                            gid:0,
                            src:'./images/1539766466773_imgWap_tmndir.png',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1539766649573_imgWap_tmndir.png'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1539766807929_imgWap_tmndir.png'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1562748158431_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1539767177903_imgWap_tmndir.png'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1562748158431_imgApp_tmndir.jpg'
                        },
                        {
                            gid:6,
                            src:'./images/1539766466773_imgWap_tmndir.png',
                            words:'商品'
                        },
                        {
                            id:7,
                            words:'商品',
                            src:'./images/1539766649573_imgWap_tmndir.png'
                        },
                        {
                            id:8,
                            words:'商品',
                            src:'./images/1539766807929_imgWap_tmndir.png'
                        },
                        {
                            id:9,
                            words:'商品',
                            src:'./images/1562748158431_imgApp_tmndir.jpg'
                        },
                        {
                            id:10,
                            words:'商品',
                            src:'./images/1539767177903_imgWap_tmndir.png'
                        },
                        {
                            id:11,
                            words:'商品',
                            src:'./images/1562748158431_imgApp_tmndir.jpg'
                        },
                        {
                            gid:12,
                            src:'./images/1539766466773_imgWap_tmndir.png',
                            words:'商品'
                        },
                        {
                            id:13,
                            words:'商品',
                            src:'./images/1539766649573_imgWap_tmndir.png'
                        },
                        {
                            id:14,
                            words:'商品',
                            src:'./images/1539766807929_imgWap_tmndir.png'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1562748158431_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1539767177903_imgWap_tmndir.png'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1562748158431_imgApp_tmndir.jpg'
                        },
                        {
                            gid:0,
                            src:'./images/1539766466773_imgWap_tmndir.png',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1539766649573_imgWap_tmndir.png'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1539766807929_imgWap_tmndir.png'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1562748158431_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1539767177903_imgWap_tmndir.png'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1562748158431_imgApp_tmndir.jpg'
                        }

                    ]
                },
                {
                    name:'生活家电',
                    id:0,
                    list:[
                        {
                            gid:0,
                            src:'./images/1529150369166_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1531125859962_imgApp_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1531129272446_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1531130118157_imgApp_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            gid:0,
                            src:'./images/1529150369166_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1531125859962_imgApp_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1531129272446_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1531130118157_imgApp_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            gid:0,
                            src:'./images/1529150369166_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1531125859962_imgApp_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1531129272446_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1531130118157_imgApp_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            gid:0,
                            src:'./images/1529150369166_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1531125859962_imgApp_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1531129272446_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1531130118157_imgApp_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            gid:0,
                            src:'./images/1529150369166_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1531125859962_imgApp_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1531129272446_imgApp_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1531130118157_imgApp_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1531128746039_imgApp_tmndir.jpg'
                        }
                    ]
                },
                {
                    name:'食品酒水',
                    id:0,
                    list:[
                        {
                            gid:0,
                            src:'./images/1541121708927_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1541121977684_imgWap_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1541122046050_imgWap_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1545719641809_imgWap_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1545723083037_imgWap_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1541122046050_imgWap_tmndir.jpg'
                        },
                        {
                            gid:0,
                            src:'./images/1541121708927_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1541121977684_imgWap_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1541122046050_imgWap_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1545719641809_imgWap_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1545723083037_imgWap_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1541122046050_imgWap_tmndir.jpg'
                        },
                        {
                            gid:0,
                            src:'./images/1541121708927_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1541121977684_imgWap_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1541122046050_imgWap_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1545719641809_imgWap_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1545723083037_imgWap_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1541122046050_imgWap_tmndir.jpg'
                        },
                        {
                            gid:0,
                            src:'./images/1541121708927_imgWap_tmndir.jpg',
                            words:'商品'
                        },
                        {
                            id:1,
                            words:'商品',
                            src:'./images/1541121977684_imgWap_tmndir.jpg'
                        },
                        {
                            id:2,
                            words:'商品',
                            src:'./images/1541122046050_imgWap_tmndir.jpg'
                        },
                        {
                            id:3,
                            words:'商品',
                            src:'./images/1545719641809_imgWap_tmndir.jpg'
                        },
                        {
                            id:4,
                            words:'商品',
                            src:'./images/1545723083037_imgWap_tmndir.jpg'
                        },
                        {
                            id:5,
                            words:'商品',
                            src:'./images/1541122046050_imgWap_tmndir.jpg'
                        }
                    ]
                }
        ]

        }
        return a
    }
}